FROM node:18-alpine

WORKDIR /app

# 复制后端代码
COPY server ./server
WORKDIR /app/server
RUN npm install

# 复制前端代码
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

# 生成 Prisma Client
WORKDIR /app/server
RUN npx prisma generate

# 暴露端口
EXPOSE 3000 5173

CMD ["npm", "run", "start:prod"]
